---
- name: Ansible user group
  ansible.builtin.group:
    name: ansible
    state: present

- name: Ansible user
  ansible.builtin.user:
    name: ansible
    shell: /bin/bash
    groups: ansible
    state: present
