---
- name: Install autofs
  apt:
    name: 'autofs'
    state: '{{nfs_server_state}}'

- name: Create directory for mounting external drives
  file:
    path: '{{nfs_server_ext_drive_mnt_point}}'
    state: "{{ (nfs_server_state == 'present') | ternary('directory', 'absent') }}"
    mode: '0750'
    group: '{{ansible_groupname}}'
  when: nfs_server_state == 'present'

- name: Create a copy of original autofs configuration file
  command:
    cmd: cp -a  /etc/auto.master /etc/auto.master.original
    creates: /etc/auto.master.original
  when: nfs_server_state == 'present'

- name: Configure autofs for external device
  copy:
    content: '{{nfs_server_ext_drive_name}}        -fstype=auto    :{{nfs_server_ext_drive_fdisk_id}}'
    dest: /etc/auto.ext
  when: nfs_server_state == 'present'
  notify: 'Restart nfs.autofs'

# umask=027 is used to set the permission to 750 ansible group only
- name: Configure autofs main file
  lineinfile:
    path: /etc/auto.master
    insertafter: 'EOF'
    line: '{{nfs_server_ext_drive_mnt_point}}   /etc/auto.ext --ghost --timeout=10,defaults,user,exec,uid={{ansible_uid}},gid={{ansible_gid}},umask=027'
    state: '{{nfs_server_state}}'
  when: nfs_server_state == 'present'
  notify: 'Restart nfs.autofs'

