- name: Install autofs
  apt:
    name: 'autofs'
    state: '{{nfs_server_state}}'

- name: Create directory for mounting external drives
  file:
    path: '/mnt/{{nfs_server_ext_drive_mnt_path}}'
    state: "{{ (nfs_server_state == 'present') | ternary('directory', 'absent') }}"
    mode: '0755'
    owner: '{{nfs_server_username}}'
    group: '{{nfs_server_groupname}}'

- name: Create a copy of original autofs configuration file
  command:
    cmd: cp -a  /etc/auto.master /etc/auto.master.original
    creates: /etc/auto.master.original
  when: nfs_server_state == 'present'

- name: Configure autofs for external device
  copy:
    content: '{{nfs_server_ext_drive_name}}        -fstype=auto    :{{nfs_server_ext_drive_fdisk_id}}'
    dest: /etc/auto.ext
  when: nfs_server_state == 'present'
  notify: 'Restart nfs.autofs'

- name: Configure autofs main file
  lineinfile:
    path: /etc/auto.master
    insertafter: 'EOF'
    line: '/mnt/{{nfs_server_ext_drive_mnt_path}}   /etc/auto.ext --ghost --timeout=10,defaults,user,exec,uid={{nfs_server_uid}}'
    state: '{{nfs_server_state}}'
  when: nfs_server_state == 'present'
  notify: 'Restart nfs.autofs'

- name: (Cleanup) Remove auto.ext
  command:
    cmd: rm -f /etc/auto.ext
    removes: /etc/auto.ext
  when: nfs_server_state == 'absent'

- name: (Cleanup) Remove auto.master
  command:
    cmd: rm -f  /etc/auto.master
    removes: /etc/auto.master
  when: nfs_server_state == 'absent'

- name: (Cleanup) Restore /etc/auto.master Uninstall does bring it back to original state, therefore this is required.
  command:
    cmd: mv /etc/auto.master.original /etc/auto.master
    removes: /etc/auto.master.original
  when: nfs_server_state == 'absent'

- name: (Cleanup) Evaluate mount path base directory
  shell:
    cmd: echo '{{nfs_server_ext_drive_mnt_path}}' | cut -d '/' -f2
  register: ext_drive_mnt_path_basedir

- name: (Cleanup) Print mount path base directory
  debug:
    var: ext_drive_mnt_path_basedir.stdout

