---
- name: Install and configure autofs
  include_tasks: autofs.yml

- name: Install NFS server
  apt:
    name: 'nfs-kernel-server'
    state: '{{nfs_server_state}}'

- name: Configure NFS server - move original config file
  command:
    cmd:  mv /etc/exports /etc/exports.original
    creates: /etc/exports.original
    removes: /etc/exports
  when: nfs_server_state == 'present'

- name: Configure NFS server
  copy:
    content: '{{nfs_server_ext_drive_mnt_path}}/{{nfs_server_ext_drive_name}} {{nfs_server_subnet}}/{{nfs_server_subnet_mask}}(rw,no_subtree_check)'
    dest: /etc/exports
  when: nfs_server_state == 'present'
  notify: Restart nfs.server

- name: (Cleanup) Remove /etc/exports
  command:
    cmd: rm -f /etc/exports
    removes: /etc/exports
  when: nfs_server_state == 'absent'

- name: (Cleanup) Restore original config file
  command:
    cmd: mv /etc/exports.original /etc/exports
    removes: /etc/exports.original
  when: nfs_server_state == 'absent'
