---
- name: Install and configure autofs
  include_tasks: autofs.yml

- name: Install NFS server
  apt:
    name: 'nfs-kernel-server'
    state: '{{nfs_server_state}}'

- name: Configure NFS server - move original config file
  command:
    cmd:  mv /etc/exports /etc/exports.original
    creates: /etc/exports.original
    removes: /etc/exports

- name: Configure NFS server
  copy:
    content: '{{nfs_server_ext_drive_mntpath}}/{{nfs_server_ext_drive_name}} {{nfs_server_subnet}}/{{nfs_server_subnet_mask}}(rw,no_subtree_check)'
    dest: /etc/exports
  notify: Restart nfs.server
