---
nfs_server_state: present
nfs_server_username: ansible
nfs_server_groupname: ansible
nfs_server_uid: 2000

nfs_server_ext_drive_mntpath: '/mnt/usbs'
nfs_server_ext_drive_name: "{{ undef(hint='External drive name is required') }}"
nfs_server_ext_drive_fdiskid: "{{ undef(hint='External drive diskid is required') }}"
