---
nfs_server_state: present
nfs_server_username: ansible
nfs_server_groupname: ansible
nfs_server_uid: 2000

# Mount paths will always be prefixed with /mnt. For example mount path /usbs will create evaluate to /mnt/usbs being created as a mount point
nfs_server_ext_drive_mnt_path: 'usbs'
nfs_server_ext_drive_name: "{{ undef(hint='External drive name is required') }}"
nfs_server_ext_drive_fdisk_id: "{{ undef(hint='External drive diskid is required') }}"
nfs_server_subnet: "{{ undef(hint='NFS server subnet is required') }}"
nfs_server_subnet_mask: "{{ undef(hint='NFS server subnet mask is required') }}"