---
- name: Install nfs-common
  apt:
    name: 'nfs-common'
    state: '{{nfs_client_state}}'

- name: Prepare mount point
  file:
    path: '{{nfs_client_mount_point}}'
    state: 'directory'
    mode: '0755'
    owner: '{{nfs_client_username}}'
    group: '{{nfs_client_groupname}}'
  when: nfs_client_state == 'present'

- name: Mount NFS volume
  ansible.posix.mount:
    src: '{{nfs_server_ip_or_hostname}}:{{nfs_server_share_path}}'
    path: '{{nfs_client_mount_point}}'
    opts: rw,sync,hard
    state: "{{ (nfs_client_state == 'present') | ternary('mounted', 'unmounted') }}"
    fstype: nfs

- name: () Cleanup mount path
  file:
    path: '{{nfs_client_mount_point}}'
    state: 'directory'
    mode: '0755'
    owner: '{{nfs_client_username}}'
    group: '{{nfs_client_groupname}}'
  when: nfs_client_state == 'present'
