#- name: Create a k8s namespace
#  kubernetes.core.k8s:
#    name: {{ nextcloud_name }}
#    api_version: v1
#    kind: Namespace
#    state: present
#  when: nextcloud_state == "present"
#
#- name: Provision postgresql db server
#  kubernetes.core.k8s:
#    state: present
#    namespace: {{ nextcloud_namespace }}
#    template: 'pgsql.server.j2'
#  when: nextcloud_state == "present"

- name: testing here
  debug:
      msg: "Hello World {{k3s_first_cn}}"

