- name: Create a k8s namespace
  kubernetes.core.k8s:
    name: "{{ nextcloud_name }}"
    api_version: v1
    kind: Namespace
    state: present
    kubeconfig: "{{ k3s_kubeconfig_path }}"
  when: nextcloud_state == "present"

- name: Provision postgresql db server
  kubernetes.core.k8s:
    state: present
    namespace: "{{ nextcloud_namespace }}"
    template: 'pgsql.server.j2'
    kubeconfig: "{{ k3s_kubeconfig_path }}"
  when: nextcloud_state == "present"

- name: (Cleanup) Deprovision postgresql db server
  kubernetes.core.k8s:
    state: absent
    namespace: "{{ nextcloud_namespace }}"
    template: 'pgsql.server.j2'
    kubeconfig: "{{ k3s_kubeconfig_path }}"
  when: nextcloud_state == "absent"

