k3s_dn_state: present

# interface which will be used for flannel
k3s_dn_flannel_iface: "eth0"

# The IP on which the node is reachable in the cluster.
# Here, a sensible default is provided, you can still override
# it for each of your hosts, though.
k3s_dn_node_ip: "{{ ansible_facts[(k3s_cn_flannel_iface)]['ipv4']['address'] }}"

k3s_dn_extra_args: >-
  --flannel-iface={{ k3s_dn_flannel_iface }}
  --node-ip={{ k3s_dn_node_ip }}