# - name: Deploy nfs storage class provisioner
#   template:
#     src: "nfs.helmchart.j2"
#     dest: "/var/lib/rancher/k3s/server/manifests/nfs.yml"
#     owner: root
#     group: root
#     mode: 0644
#   when: k3s_first_cn and nfs_sc_state == "present"

# - name: (Cleanup) Undeploy nfs storage class provisioner
#   file:
#     path: "/var/lib/rancher/k3s/server/manifests/nfs.yml"
#     state: absent
#   when: k3s_first_cn and nfs_sc_state == "absent"

- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: stable
    repo_url: "https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner"

- name: Install nfs storage class provisioner
  kubernetes.core.helm:
    name: nfs
    chart_ref: stable/nfs-subdir-external-provisioner
    namespace: default
    state: "{{ nfs_sc_state }}"
    values: 
      nfs:
        server: "{{ nfs_server_ip }}"
        path: "{{ nfs_export_path }}"
      storageClass:
        reclaimPolicy: Retain
        name: "{{ nfs_sc_name }}"
      podSecurityContext:
        fsGroup: "{{ ansible_gid }}"
        runAsUser: "{{ ansible_uid }}"
        runAsGroup: "{{ ansible_gid }}"
      securityContext:
        fsGroup: "{{ ansible_gid }}"
        runAsUser: "{{ ansible_uid }}"
        runAsGroup: "{{ ansible_gid }}"

