- hosts: nfs_server
  gather_facts: true
  become: yes
  roles:
    - role: roles/nfs_server
      nfs_server_state: 'present'
      nfs_server_ext_drive_fdiskid: /dev/sda1
      nfs_server_ext_drive_name: pioneer1
      nfs_server_subnet: 192.168.86.0
      nfs_server_subnet_mask: 255.255.255.0

- hosts: nfs_clients
  gather_facts: true
  become: yes
  roles:
    - role: roles/nfs_clients
      nfs_client_state: 'present'
      nfs_server_ip_or_hostname: nfs
      nfs_server_share_path: /mnt/usbs/pioneer1
      nfs_client_mount_point: /mnt/nfs/pioneer1
