- hosts: nfs_clients
  gather_facts: true
  become: yes
  roles:
    - role: roles/nfs_clients
      nfs_client_state: 'present'
      nfs_server_ip_or_hostname: nfs
      nfs_server_share_path: /mnt/usbs/pioneer1
      nfs_client_mount_point: /mnt/nfs/pioneer1
