- hosts: nfs_clients
  gather_facts: false
  become: yes
  vars:
    nfs_mount_point: '/mnt/nfs/pioneer1'
  tasks:
    - name: check mountpoint and store in var
      command: mountpoint {{nfs_mount_point}}
      register: mountpoint_check

    - debug:
        msg: "{{mountpoint_check.stdout}}"

    - name: is unmounted check
      debug:
        msg: is unmounted
      when: "'is not a mountpoint' in mountpoint_check.stdout"




#    - name: 1
#      debug:
#        msg: 1 is mounted - {{is_mounted}}
#      vars:
#        is_mounted: "{{ '/mnt/nfs/pioneer1' is ansible.builtin.is_mount}}"
#
#    - name: 2
#      debug:
#        msg: 2 is mounted - {{is_mounted}}
#      vars:
#        is_mounted: "{{ '/mnt/nfs' is is_mount}}"
#
#    - name: 3
#      debug:
#        msg: 3 is mounted - {{is_mounted}}
#      vars:
#        is_mounted: "{{  '/mnt/nfs/pioneer1' is mount}}"


#    - name: check if {{nfs_mount_point}} is mounted using (mount)
#      debug:
#        msg: is {{nfs_mount_point}} mounted - {{is_mounted}}
#      vars:
#        is_mounted: {{nfs_mount_point}} is mount
#
#    - name: check if {{nfs_mount_point}} is unmounted using (is_mount)
#      debug:
#        msg: is {{nfs_mount_point}} unmounted - {{is_unmounted}}
#      vars:
#        is_unmounted: {{nfs_mount_point}} is not is_mount
#
#    - name: check if {{nfs_mount_point}} is unmounted using (mount)
#      debug:
#        msg: is {{nfs_mount_point}} unmounted - {{is_unmounted}}
#      vars:
#        is_unmounted: {{nfs_mount_point}} is not mount
#
#    - name: extrapolated string check mount method
#      debug:
#        msg: is {{nfs_mount_point}} unmounted - {{is_unmounted}}
#      vars:
#        is_unmounted: "{{nfs_mount_point is not is_mount}}"
#
#    - name: extrapolated string check is_mount method
#      debug:
#        msg: is {{nfs_mount_point}} unmounted - {{is_unmounted}}
#      vars:
#        is_unmounted: "{{nfs_mount_point is not is_mount}}"