---
- name: Download k3s binary arm64
  get_url:
    url: https://github.com/k3s-io/k3s/releases/download/{{ k3s_cluster_version }}/k3s-arm64
    checksum: sha256:https://github.com/k3s-io/k3s/releases/download/{{ k3s_cluster_version }}/sha256sum-arm64.txt
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: 0755
  when: k3s_cluster_state == 'present'

# This step is required during image creation time
#- name: Enable cgroup via boot commandline if not already enabled for Ubuntu on a Raspberry Pi
#  lineinfile:
#    path: /boot/firmware/cmdline.txt
#    backrefs: yes
#    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
#    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
#  notify: reboot

- name: Install linux-modules-extra-raspi
  apt:
    name: linux-modules-extra-raspi
    state: '{{k3s_cluster_state}}'

- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: '{{k3s_cluster_state}}'
    reload: yes

- name: Enable IPv6 forwarding
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: '{{k3s_cluster_state}}'
    reload: yes

- name: Enable IPv6 router advertisements
  sysctl:
    name: net.ipv6.conf.all.accept_ra
    value: "2"
    state: '{{k3s_cluster_state}}'
    reload: yes

- name: Install python3-pip
  apt:
    name: python3-pip
    state: '{{k3s_cluster_state}}'

- name: Install pre-requisites for executing k8s and k3s modules
  pip:
    name:
      - openshift
      - pyyaml
      - kubernetes
      - jsonpatch
    state: '{{k3s_cluster_state}}'