---
- name: Download k3s binary arm64
  get_url:
    url: https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/k3s-arm64
    checksum: sha256:https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/sha256sum-arm64.txt
    dest: '{{systemd_dir}}'
    owner: root
    group: root
    mode: 0755

# This step is required during image creation time
#- name: Enable cgroup via boot commandline if not already enabled for Ubuntu on a Raspberry Pi
#  lineinfile:
#    path: /boot/firmware/cmdline.txt
#    backrefs: yes
#    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
#    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
#  notify: reboot

- name: Install linux-modules-extra-raspi
  apt:
    name: linux-modules-extra-raspi
    state: present

- name: Set timezone to UTC
  community.general.timezone:
    name: '{{system_timezone}}'

- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes

- name: Enable IPv6 forwarding
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: yes

- name: Enable IPv6 router advertisements
  sysctl:
    name: net.ipv6.conf.all.accept_ra
    value: "2"
    state: present
    reload: yes