- name: Create directory for mounting external drives
  ansible.builtin.file:
    path: '{{nfs_server_ext_drive_mntpath}}'
    state: "{{ (nfs_server_state == 'present') | ternary('directory', 'absent') }}"
    mode: '0755'

- name: Install autofs
  apt:
    name: 'autofs'
    state: '{{nfs_server_state}}'

- name: Check if the autofs main configuration file exists
  ansible.builtin.stat:
    path: '/etc/auto.master'
  register: autofs_config_file

- name: Create a copy of original autofs configuration file
  ansible.builtin.copy:
    src: /etc/auto.master
    dest: /etc/auto.master.orig
    owner: '{{nfs_server_username}}'
    group: '{{nfs_server_groupname}}'
    mode: '0644'
  when: autofs_config_file.stat.exists and autofs_config_file.stat.isreg

- name: Configure autofs for external device
  ansible.builtin.copy:
    content: '{{nfs_server_ext_drive_name}}        -fstype=auto    :{{nfs_server_ext_drive_fdiskid}}'
    dest: /etc/auto.ext-usb
    notify: 'Restart autofs'
  when: nfs_server_state == 'present'

- name: Configure autofs main file
  ansible.builtin.lineinfile:
    path: /etc/auto.master
    insertafter: 'EOF'
    line: '{{nfs_server_ext_drive_mntpath}}   /etc/auto.ext-usb --ghost --timeout=10,defaults,user,exec,uid={{nfs_server_uid}}'
    notify: 'Restart autofs'
  when: autofs_config_file.stat.exists and autofs_config_file.stat.isreg