---
- name: Create directory for mounting external drives
  ansible.builtin.file:
    path: '/mnt/usbs'
    state: "{{ (nfs_state == 'present') | ternary('directory', 'absent') }}"
    mode: '0755'

- name: Install autofs
  apt:
    name: "autofs"
    state: "present"
    become: true

- name: Create a copy of original autofs configuration file
  ansible.builtin.copy:
    src: /etc/auto.master
    dest: /etc/auto.master.orig
    owner: {{ nfs_user }}
    group: {{ nfs_groupname }}
    mode: '0644'
    become: true

- name: Configure autofs for usb device
  ansible.builtin.copy:
    src: '{{nfs_ext_drive_name}}        -fstype=auto    :{{nfs_ext_drive_fdiskid}}'
    dest: /etc/auto.ext-usb
    become: true

- name: Configure autofs main file
  ansible.builtin.lineinfile:
    path: /etc/auto.master
    insertafter: 'EOF'
    line: '{{nfs_ext_drive_mntpath}}   /etc/auto.ext-usb --ghost --timeout=10,defaults,user,exec,uid={{nfs_uid}}'
    become: true
    notify: 'restart autofs'