---
- name: Run tasks from main file in ansible managed node module
  import_role:
    name: ansible_managed_nodes
    tasks_from: ansible_user
  vars:
    amn_state: '{{acn_state}}'

- name: Check if the .ssh directory exists
  stat:
    path: '{{ansible_userhome}}/.ssh'
  register: ansible_user_ssh_dir

# For state - absent this file will be removed as a part of directory deletion
- name: Generate an OpenSSH keypair using ed25519
  community.crypto.openssh_keypair:
    path: '{{ansible_userhome}}/.ssh/id_rsa'
    owner: '{{ansible_username}}'
    group: '{{ansible_groupname}}'
    type: ed25519
  when: ansible_user_ssh_dir.stat.isdir is defined and ansible_user_ssh_dir.stat.isdir

- name: Set timezone to UTC
  community.general.timezone:
    name: '{{system_timezone}}'

- name: Install python3-pip
  apt:
    name: python3-pip
    state: present
  when: acn_state == 'present'

- name: Install pre-requisites for executing k8s and k3s modules
  pip:
    name:
      - openshift
      - pyyaml
      - kubernetes
      - jsonpatch
    state: present
    when: acn_state == 'present'

- name: (Cleanup) Uninstall pre-requisites for executing k8s and k3s modules
  pip:
    name:
      - openshift
      - pyyaml
      - kubernetes
      - jsonpatch
    state: absent
    when: acn_state == 'absent'

- name: (Cleanup) Uninstall python3-pip
  apt:
    name: python3-pip
    state: absent
  when: acn_state == 'absent'