---
# Download logs of k3s-init.service from the nodes to localhost.
# Note that log_destination must be set.

- name: Fetch k3s-init.service logs
  ansible.builtin.command:
    cmd: journalctl --all --unit=k3s-init.service
  changed_when: false
  register: k3s_init_log

- name: Create {{ k3s_cn_log_destination }}
  delegate_to: localhost
  run_once: true
  ansible.builtin.file:
    path: "{{ k3s_cn_log_destination }}"
    state: directory
    owner: '{{ansible_username}}'
    group: '{{ansible_groupname}}'
    mode: "0755"

- name: Store logs to {{ k3s_cn_log_destination }}
  delegate_to: localhost
  ansible.builtin.template:
    src: content.j2
    dest: "{{ k3s_cn_log_destination }}/k3s-init@{{ ansible_hostname }}.log"
    owner: '{{ansible_username}}'
    group: '{{ansible_groupname}}'
    mode: 0644
  vars:
    content: "{{ k3s_init_log.stdout }}"
