---
- name: Ansible user group
  group:
    name: '{{amn_groupname}}'
    gid: '{{amn_gid}}'
    state: '{{amn_state}}'

- name: Ansible user
  user:
    name: '{{amn_username}}'
    uid: '{{amn_uid}}'
    shell: /bin/bash
    groups: '{{amn_groupname}}'
    home: '{{amn_userhome}}'
    state: '{{amn_state}}'

- name: Create .ssh directory
  file:
    path: '{{amn_userhome}}/.ssh'
    state: "{{ (amn_state == 'present') | ternary('directory', 'absent') }}"
    mode: '0755'
