---
- name: Ansible user group
  group:
    name: '{{ansible_groupname}}'
    gid: '{{ansible_gid}}'
    state: '{{amn_state}}'

- name: Ansible user
  user:
    name: '{{ansible_username}}'
    uid: '{{ansible_uid}}'
    shell: /bin/bash
    groups: '{{ansible_groupname}}'
    home: '{{ansible_userhome}}'
    state: '{{amn_state}}'

- name: Create .ssh directory
  file:
    path: '{{ansible_userhome}}/.ssh'
    state: "{{ (amn_state == 'present') | ternary('directory', 'absent') }}"
    mode: '0755'
