---
- name: Ansible user group
  ansible.builtin.group:
    name: '{{amn_groupname}}'
    gid: '{{amn_gid}}'
    state: '{{amn_state}}'

- name: Ansible user
  ansible.builtin.user:
    name: '{{amn_username}}'
    uid: '{{amn_uid}}'
    shell: /bin/bash
    groups: '{{amn_groupname}}'
    home: '{{amn_userhome}}'
    state: '{{amn_state}}'


