#- name: Copy K3s service file
#  template:
#    src: "k3s.service.j2"
#    dest: "{{ systemd_dir }}/k3s-node.service"
#    owner: root
#    group: root
#    mode: 0755
#  when: k3s_dn_state == 'present'
#
#- name: Enable and check K3s service
#  systemd:
#    name: k3s-node
#    daemon_reload: true
#    state: restarted
#    enabled: true
#  when: k3s_dn_state == 'present'
#
#- name: (Cleanup) Stop k3s service
#  systemd:
#      name: k3s-node
#      state: stopped
#      enabled: false
#  when: k3s_dn_state == 'absent'

#- name: (Cleanup) Remove k3s service file
#  file:
#      path: "{{ systemd_dir }}/k3s-node.service"
#      state: absent
#  when: k3s_dn_state == 'absent'

- name: Display all variables/facts known for a host
  ansible.builtin.debug:
    var: hostvars['ayuraya']
    verbosity: 4